django_labs/django_labs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls'))
]

django_labs/todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.index, name='all-tasks'),
    path('<int:id>', views.show, name='task-details'),
    path('done/<int:id>', views.mark_task_as_done, name='task-done'),
    path('not-done/<int:id>', views.mark_task_as_not_done, name='task-not-done'),
    path('delete/<int:id>', views.delete_task, name='delete-task'),
    path('refresh-list', views.refresh_list, name='refresh-tasks-list'),
    path('weather-Api', views.api_call, name='weather-api'),



]

django_labs/todo/views.py
from copy import deepcopy

from django.contrib import messages
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse

tasks = [
    {'name': 'do some thing', 'description': 'eat champions breakfast', 'is_done': False, 'priority': 1},
    {'name': 'walk the dog', 'description': 'walk zeus along the sea ', 'is_done': False, 'priority': 2},
    {'name': 'finish work', 'description': 'finish work tasks', 'is_done': False, 'priority': 4},
    {'name': 'do another thing', 'description': 'add any desc here', 'is_done': False, 'priority': 5}

]

backup_list = deepcopy(tasks)


def index(request):
    return render(request, 'todo/index.html', context={'tasks': tasks})


def show(request, **kwargs):
    task_id = kwargs.get('id')
    founded_task = tasks[task_id - 1]
    return render(request, 'todo/taskDetails.html', context={'task': founded_task})


def mark_task_as_done(request, **kwargs):
    task_id = kwargs.get('id')
    founded_task = tasks[task_id - 1]
    founded_task['is_done'] = True
    messages.success(request, f'Well done dude ! task : {founded_task["name"]} is done')
    return redirect(reverse('todo:all-tasks'))


def mark_task_as_not_done(request, **kwargs):
    task_id = kwargs.get('id')
    founded_task = tasks[task_id - 1]
    founded_task['is_done'] = False
    messages.warning(request, f'Well sh** happens ! task : {founded_task["name"]} is not done')
    return redirect(reverse('todo:all-tasks'))


def delete_task(request, **kwargs):
    task_id = kwargs.get('id')
    founded_task = tasks[task_id - 1]
    tasks.pop(task_id - 1)
    messages.info(request, f' task : {founded_task["name"]} is deleted')
    return redirect(reverse('todo:all-tasks'))


def refresh_list(request):
    global tasks
    tasks = deepcopy(backup_list)
    messages.success(request, f'list refreshed ')
    return redirect(reverse('todo:all-tasks'))


def api_call(request):
    return render(request, 'todo/apiCall.html')

django_labs/todo/templates/todo/apiCall.html
{% extends 'todo/base.html'%}

{% block title %} All-Tasks {% endblock %}

{% load c_tag %}

{% block content %}

{% get_weather as weather_tag %}

<div class="card mb-3 offset-2 col-8">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="https:{{weather_tag.current.condition.icon}}" class="card-img-top" alt="...">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">
                    {{weather_tag.location.name}}-{{weather_tag.location.region}}-{{weather_tag.location.country}}</h5>
                {% for detail,value in weather_tag.location.items %}
                <p class="card-text">{{detail}} : {{value}} </p>
                {% endfor %}


                <a href="{% url 'todo:all-tasks' %}" class="btn btn-primary">Go Back</a>
            </div>
        </div>
    </div>
    <div class="row px-2">
        <div class="col-8 offset-2">
            <div class="card border-primary mb-3">
                <div class="card-header">Conditions</div>
                <div class="card-body text-primary">
                    <h5 class="card-title">temperature</h5>
                    {% for detail,value in weather_tag.current.items %}
                    {% if detail == "condition" %}
                    {% else %}

                    <p class="card-text">{{detail}} : {{value}} </p>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>

    </div>
</div>
</div>
{% endblock %}

django_labs/todo/templates/todo/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <title>  {% block title %} Home {% endblock %}</title>
</head>
<body>

{% include "todo/navbar.html"%}

<div class="container mt-4 bg-light">
    {% block content%}

    {% endblock %}
</div>


</body>
</html>

django_labs/todo/templates/todo/index.html
{% extends 'todo/base.html'%}

{% block title %} All-Tasks {% endblock %}


{% block content %}



{% if messages %}

{% for message in messages %}
{% if message.tags == 'info' %}
<div class="alert alert-danger" role="alert">
    {% else %}
    <div class="alert alert-{{ message.tags }}" role="alert">
        {% endif %}
        {{ message }}
    </div>
    {% endfor %}


    {% endif %}

    <table class="table table-striped table-hover caption-top">
        <caption class="offset-11">
            <a
                    class="btn btn-sm btn-info"
                    href="{% url 'todo:refresh-tasks-list'  %}"
            >Refresh</a>

        </caption>
        <thead class="table-info">
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Desc.</th>
            <th scope="col">status</th>
            <th scope="col">Priority</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for task in tasks %}
        <tr>
            <th scope="row">{{forloop.counter}}</th>
            <th scope="row">{{task.name}}</th>
            <td>{{task.description}}</td>
            <td>{{task.is_done}}</td>
            <td>{{task.priority}}</td>
            <td>
                <a
                        class="btn btn-sm btn-primary"
                        href="{% url 'todo:task-details' forloop.counter %}"
                >Details</a>
                {% if not task.is_done %}
                <a
                        class="btn btn-sm btn-success"
                        href="{% url 'todo:task-done' forloop.counter %}"
                >Mark-Done</a>
                {% else %}
                <a
                        class="btn btn-sm btn-warning"
                        href="{% url 'todo:task-not-done' forloop.counter %}"
                >Mark-NotDone</a>
                <a
                        class="btn btn-sm btn-danger"
                        href="{% url 'todo:delete-task' forloop.counter %}"
                >Delete</a>

                {% endif %}
            </td>

        </tr>
        {% endfor%}
        </tbody>
    </table>
    {% endblock %}

django_labs/todo/templates/todo/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">ToDo-App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page"  href="{% url 'todo:all-tasks' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todo:weather-api' %}">Weather-Api</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Contact-Us</a>
        </li>

      </ul>
    </div>
  </div>
</nav>

django_labs/todo/templates/todo/taskDetails.html
{% extends 'todo/base.html'%}

{% block title %} Task-{{task.name}} {% endblock %}

{% block content %}

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">{{task.name}} </h5>
    <p class="card-text">{{task.description}} </p>
    <a href="{% url 'todo:all-tasks' %}" class="btn btn-primary">Go Back</a>
  </div>
</div>
{% endblock %}