movie-app/movie_app/Actors/api/v1/urls.py
from django.urls import path
from . import views

app_name = 'Actors-api-v1'
urlpatterns = [
    path('', views.index, name='all-Actors'),
    path('<int:pk>', views.ShowActor.as_view(), name='show'),
    # path('create', views.add_movie, name='create'),
    # path('<int:id>', views.show, name='show'),
    # path('delete/<int:id>', views.delete_movie, name='delete-movie'),
    # path('Edit/<int:id>', views.edit, name='edit-movie'),
]

movie-app/movie_app/Actors/urls.py
from django.urls import path
from . import views

app_name = 'Actors'
urlpatterns = [
    path('', views.index, name='all-Actors'),
    path('create', views.add_actor, name='create'),
    path('<int:id>', views.show, name='show'),
    path('delete/<int:id>', views.delete_actor, name='delete-actor'),
    path('Edit/<int:id>', views.edit, name='edit-actor'),
]

movie-app/movie_app/movie_app/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('',TemplateView.as_view(template_name='home.html'),name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('Accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('Actors/', include('Actors.urls')),
    path('Movies/', include('Movies.urls')),
    path('api/movies/', include('Movies.api.v1.urls')),
    path('api/accounts/', include('Accounts.api.v1.urls')),
    path('api/actors/', include('Actors.api.v1.urls')),
]
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie-app/movie_app/Actors/models.py
from django.db import models


class Actor(models.Model):
    GENDER = (('M', 'M'), ('F', 'F'))
    name = models.fields.CharField(max_length=60)
    gender = models.fields.CharField(choices=GENDER, max_length=1, default='M')
    profile_picture = models.ImageField(default='default.png', upload_to='actors')

    def __str__(self):
        return self.name

movie-app/movie_app/Actors/forms.py
from django import forms

from .models import Actor


class ActorForm(forms.ModelForm):
    class Meta:
        model = Actor
        fields = '__all__'
        # ('name', 'gender', 'profile_picture')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'gender': forms.Select(attrs={'class': 'form-select '}),
            'profile_picture': forms.FileInput(attrs={'class': 'form-control'})
        }

movie-app/movie_app/Actors/api/v1/views.py
from django.urls import path, include
from django.contrib.auth.models import User
from rest_framework import status, routers, serializers, viewsets
from rest_framework.generics import RetrieveAPIView
from rest_framework.response import Response
from rest_framework.decorators import api_view

from .serializers import ActorSerializer
from ...models import Actor


@api_view(['GET'])
def index(request):
    all_movies = Actor.objects.all()
    serializer = ActorSerializer(all_movies, many=True)
    return Response(data=serializer.data, status=status.HTTP_200_OK)


class ShowActor(RetrieveAPIView):
    queryset = Actor.objects.all()
    serializer_class = ActorSerializer

movie-app/movie_app/Actors/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, reverse

from .forms import ActorForm
from .models import Actor


def index(request):
    actors = Actor.objects.all()
    return render(request, 'Actors/Actors_list.html', {'actors': actors})


def add_actor(request):
    if request.method == 'POST':
        form = ActorForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect(reverse('Actors:all-Actors'))
    else:
        form = ActorForm()
    return render(request, 'Actors/create_actor.html', {'form': form})


def show(request, **kwargs):
    pass


def delete_actor(request, **kwargs):
    actor_id = kwargs.get('id')
    Actor.objects.filter(id=actor_id).delete()
    messages.warning(request, f'Well actor NO. {actor_id} is deleted')
    return redirect(reverse('Actors:all-Actors'))


def edit(request, id):
    actor = Actor.objects.get(pk=id);

    if request.method == 'GET':
        form = ActorForm(instance=actor)
        return render(request, 'Actors/edit_actor.html', {'form': form, 'actor': actor})
    else:
        form = ActorForm(request.POST, request.FILES, instance=actor)
        if form.is_valid():
            actor = form.save()
            messages.success(request, f'Well actor NO. {actor.id} is updated')
            return redirect(reverse('Actors:all-Actors'))

movie-app/movie_app/templates/Actors/Actors_list.html
{% extends 'base_layout.html'%}

{% block title %} Actors {% endblock %}
{% block content %}
{% if messages %}

{% for message in messages %}
{% if message.tags == 'info' %}
<div class="alert alert-danger" role="alert">
    {% else %}
    <div class="alert alert-{{ message.tags }}" role="alert">
        {% endif %}
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    <div class="container mt-4 bg-info shadow-lg p-3 mb-5 rounded ">
        <div class="col-4">

            <a class="btn btn-sm btn-success col-4 ms-3 shadow-lg "
               href="{% url 'Actors:create' %}">Add-Actor</a>
        </div>
        <div class="row p-2">
            {% for actor in actors %}
            <div class="card col-3 me-2 border-2 border-primary p-1">
                <img src="{{ actor.profile_picture.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{actor.name}}-{{actor.gender}}</h5>
                    <p class="card-text">{{ actor.id}}</p>
                    <a class="btn btn-sm btn-primary col-4 ms-3 shadow-lg "
                       href="{% url 'Actors:edit-actor' actor.id  %}">Edit</a>
                    <a class="btn btn-sm btn-danger col-4 ms-3 shadow-lg "
                       href="{% url 'Actors:delete-actor' actor.id  %}">Delete</a>
                </div>
            </div>
            {% endfor%}
        </div>
    </div>
</div>
{% endblock %}

movie-app/movie_app/templates/Actors/create_actor.html
{% extends 'base_layout.html'%}

{% block title %} Adding-Actors {% endblock %}
{% block content %}
<div class="container mt-4 bg-info shadow-lg p-3 mb-5 rounded">
    <h5 class="shadow-lg col-2 "> Adding Actor : </h5>
    <form action="{% url 'Actors:create' %}" method="post" class="col-8 offset-2" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}


    </form>
</div>

{% endblock %}

movie-app/movie_app/templates/Actors/edit_actor.html
{% extends 'base_layout.html'%}

{% block title %} Edit-Movie {% endblock %}
{% block content %}
<div class="container mt-4 bg-info shadow-lg p-3 mb-5 rounded">
    <h5 class="shadow-lg col-2 "> Edit A-Movie : </h5>
    <form action="{% url 'Actors:edit-actor' actor.id %}" method="post" class="col-8 offset-2" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-sm btn-success col-4 offset-2 shadow-lg ">Add</button>
        <a class="btn btn-sm btn-danger col-4 ms-3 shadow-lg " href="{% url 'Actors:all-Actors' %}">Cancel</a>
    </form>
</div>

{% endblock %}