movie-app/movie_app/Actors/urls.py
from django.urls import path
from . import views

app_name = 'Actors'
urlpatterns = [
    path('', views.index, name='all-Actors'),
    path('create', views.add_actor, name='create'),
    path('<int:id>', views.show, name='show'),
    path('delete/<int:id>', views.delete_actor, name='delete-actor'),
    path('Edit/<int:id>', views.edit, name='edit-actor'),
]

movie-app/movie_app/Movies/api/v1/urls.py
from django.urls import path
from . import views

app_name = 'Movies-api-v1'

urlpatterns = [
    # generics views
    # path('', views.AllMovies.as_view(), name='all-Movies'),
    # path('<int:pk>', views.ShowMovie.as_view(), name='show'),
    # path('create', views.CreateMovie.as_view(), name='create'),
    # path('<int:pk>/edit', views.EditMovie.as_view(), name='edit'),
    # path('<int:pk>/delete', views.DeleteMovie.as_view(), name='delete'),
    # function bassed views
    path('', views.index, name='all-Movies'),
    path('create', views.create_movie, name='create'),
    path('<int:id>/edit', views.update_movie, name='edit'),
    path('<int:id>/delete', views.update_movie, name='delete'),

]

movie-app/movie_app/Movies/urls.py
from django.urls import path
from . import views

app_name = 'Movies'
urlpatterns = [
    path('', views.index, name='all-Movies'),
    path('create', views.add_movie, name='create'),
    path('<int:id>', views.show, name='show'),
    path('delete/<int:id>', views.delete_movie, name='delete-movie'),
    path('Edit/<int:id>', views.edit, name='edit-movie'),
]

movie-app/movie_app/movie_app/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('',TemplateView.as_view(template_name='home.html'),name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('Accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('Actors/', include('Actors.urls')),
    path('Movies/', include('Movies.urls')),
    path('api/movies/', include('Movies.api.v1.urls')),
    path('api/accounts/', include('Accounts.api.v1.urls')),
    path('api/actors/', include('Actors.api.v1.urls')),
]
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie-app/movie_app/Movies/models.py
from datetime import datetime

from django.db import models


class Director(models.Model):
    name = models.fields.CharField(max_length=100, verbose_name='Director', default='unknown')

    def __str__(self):
        return self.name


class Movie(models.Model):
    name = models.fields.CharField(max_length=150)
    production_year = models.fields.DateTimeField(default=datetime.now)
    creation_time = models.fields.DateTimeField(auto_now_add=True)
    update_time = models.fields.DateTimeField(auto_now=True)
    actors = models.ManyToManyField('Actors.Actor')
    director = models.OneToOneField(Director, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

movie-app/movie_app/Movies/forms.py
from django import forms

from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'actors': forms.SelectMultiple(attrs={'class': 'form-select '}),
            'production_year': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'date'}),
            'director': forms.Select(attrs={'class': 'form-select '}),
        }

movie-app/movie_app/Movies/api/v1/views.py
from django.urls import path, include
from django.contrib.auth.models import User
from rest_framework import status, routers, serializers, viewsets
from rest_framework.generics import (
    ListAPIView,
    RetrieveAPIView,
    CreateAPIView,
    UpdateAPIView,
    DestroyAPIView
)
from rest_framework.response import Response
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import TokenAuthentication

from .serializers import MovieSerializer, MovieCreateSerializer
from ...models import Movie


@api_view(['GET'])
def index(request):
    all_movies = Movie.objects.all()
    serializer = MovieSerializer(all_movies, many=True)
    return Response(data=serializer.data, status=status.HTTP_200_OK)


@api_view(['POST'])
def create_movie(request):
    response = {'data': None, 'status': status.HTTP_201_CREATED}
    serializer = MovieSerializer(date=request.data)

    if serializer.is_valid():
        serializer.save()
        response['data'] = serializer.data
    else:
        response['data'] = serializer.errors
        response['status'] = status.HTTP_400_BAD_REQUEST
    return Response(**response)


@api_view(['PUT', 'PATCH'])
def update_movie(request, id):
    movie = Movie.objects.filter(pk=id).first()
    serializer = MovieSerializer(instance=movie, data=request.data)
    if request.method == 'PATCH':
        serializer = MovieSerializer(instance=movie, data=request.data, partial=True)
    response = {'data': None, 'status': status.HTTP_201_CREATED}
    if serializer.is_valid():
        serializer.save()
        response['data'] = serializer.data
    else:
        response['data'] = serializer.errors
        response['status'] = status.HTTP_400_BAD_REQUEST
    return Response(**response)


@api_view(['DELETE'])
def delete_movie(request, id):
    Movie.objects.get(pk=id).delete()
    return Response(data={'response', 'Entry deleted'}, status=status.HTTP_204_NO_CONTENT)


class AllMovies(ListAPIView):
    queryset = Movie.objects.all()
    serializer_class = MovieSerializer


class ShowMovie(RetrieveAPIView):
    queryset = Movie.objects.all()
    serializer_class = MovieSerializer


class CreateMovie(CreateAPIView):
    queryset = Movie.objects.all()
    serializer_class = MovieCreateSerializer


class EditMovie(UpdateAPIView):
    queryset = Movie.objects.all()
    serializer_class = MovieSerializer


class DeleteMovie(DestroyAPIView):
    queryset = Movie.objects.all()
    serializer_class = MovieSerializer

movie-app/movie_app/Movies/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, reverse

from .forms import MovieForm
from .models import Movie


def index(request):
    movies = Movie.objects.all()
    print(movies)
    return render(request, 'Movies/Movies_list.html', {'movies': movies})

@login_required
def add_movie(request):
    if request.method == 'POST':
        form = MovieForm(request.POST, request.FILES)
        if form.is_valid():
            movie = form.save()
            return redirect(reverse('Movies:all-Movies'))
    else:
        form = MovieForm()
    return render(request, 'Movies/create_movie.html', {'form': form})


def show(request, **kwargs):
    pass


def delete_movie(request, **kwargs):
    movie_id = kwargs.get('id')
    Movie.objects.filter(id=movie_id).delete()
    messages.warning(request, f'Well movie NO. {movie_id} is deleted')
    return redirect(reverse('Movies:all-Movies'))


def edit(request, id):
    movie = Movie.objects.get(pk=id);

    if request.method == 'GET':
        form = MovieForm(instance=movie)
        return render(request, 'Movies/edit_movie.html', {'form': form, 'movie': movie})
    else:
        form = MovieForm(request.POST,instance=movie)
        if form.is_valid():
            movie = form.save()
            return redirect(reverse('Movies:all-Movies'))

movie-app/movie_app/templates/Movies/Movies_list.html
{% extends 'base_layout.html'%}

{% block title %} Movies {% endblock %}
{% block content %}
{% if messages %}

{% for message in messages %}
{% if message.tags == 'info' %}
<div class="alert alert-danger" role="alert">
    {% else %}
    <div class="alert alert-{{ message.tags }}" role="alert">
        {% endif %}
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    <div class="container mt-4 bg-info shadow-lg p-3 mb-5 rounded ">
        <div class="col-4">

            <a class="btn btn-sm btn-success col-4 ms-3 shadow-lg "
               href="{% url 'Movies:create' %}">Add-A movie</a>
        </div>
        <div class="row p-2">
            {% for movie in movies %}
            <div class="card col-3 me-2 border-2 border-primary p-1">
                <div class="card-body">
                    <h5 class="card-title">{{movie.name}} - {{movie.production_year | date:"d M Y"}}</h5>
                    <p class="card-text"> <small class="text-muted">creation time : </small>{{ movie.creation_time | date:"D d M Y" }}</p>
                    <p class="card-text"><small class="text-muted">update time : </small>{{ movie.update_time | date:"D d M Y"}}</p>
                    <small class="text-muted">Actors : </small>
                     {% for actor in movie.actors.all %}
                    <h5 class="badge rounded-pill bg-info text-dark"> {{ actor.name }}</h5>
                    {% endfor %}
                    <br>
                        <small class="text-muted">Director : </small>

                    <h5 class="badge rounded-pill bg-warning text-dark"> {{ movie.director }}</h5>

                    <br>
                    <a class="btn btn-sm btn-primary col-4 ms-3 shadow-lg "
                       href="{% url 'Movies:edit-movie' movie.id  %}">Edit</a>
                    <a class="btn btn-sm btn-danger col-4 ms-3 shadow-lg "
                       href="{% url 'Movies:delete-movie' movie.id  %}">Delete</a>
                </div>
            </div>
            {% endfor%}
        </div>
    </div>
</div>
{% endblock %}

movie-app/movie_app/templates/Movies/create_movie.html
{% extends 'base_layout.html'%}

{% block title %} Adding-Movie {% endblock %}
{% block content %}
<div class="container mt-4 bg-info shadow-lg p-3 mb-5 rounded">
    <h5 class="shadow-lg col-2 "> Adding A-Movie : </h5>
    <form action="{% url 'Movies:create' %}" method="post" class="col-8 offset-2" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-sm btn-success col-4 offset-2 shadow-lg ">Add</button>
        <a class="btn btn-sm btn-danger col-4 ms-3 shadow-lg " href="{% url 'Movies:all-Movies' %}">Cancel</a>
    </form>
</div>

{% endblock %}

movie-app/movie_app/templates/Movies/edit_movie.html
{% extends 'base_layout.html'%}

{% block title %} Edit-Movie {% endblock %}
{% block content %}
<div class="container mt-4 bg-info shadow-lg p-3 mb-5 rounded">
    <h5 class="shadow-lg col-2 "> Edit A-Movie : </h5>
    <form action="{% url 'Movies:edit-movie' movie.id %}" method="post" class="col-8 offset-2" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-sm btn-success col-4 offset-2 shadow-lg ">Add</button>
        <a class="btn btn-sm btn-danger col-4 ms-3 shadow-lg " href="{% url 'Movies:all-Movies' %}">Cancel</a>
    </form>
</div>

{% endblock %}