movie-app/movie_app/Accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup', views.signup, name='signup'),

]

movie-app/movie_app/Actors/urls.py
from django.urls import path
from . import views

app_name = 'Actors'
urlpatterns = [
    path('', views.index, name='all-Actors'),
    path('create', views.add_actor, name='create'),
    path('<int:id>', views.show, name='show'),
    path('delete/<int:id>', views.delete_actor, name='delete-actor'),
    path('Edit/<int:id>', views.edit, name='edit-actor'),
]

movie-app/movie_app/Movies/urls.py
from django.urls import path
from . import views

app_name = 'Movies'
urlpatterns = [
    path('', views.index, name='all-Movies'),
    path('create', views.add_movie, name='create'),
    path('<int:id>', views.show, name='show'),
    path('delete/<int:id>', views.delete_movie, name='delete-movie'),
    path('Edit/<int:id>', views.edit, name='edit-movie'),
]

movie-app/movie_app/movie_app/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('',TemplateView.as_view(template_name='home.html'),name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('Accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('Actors/', include('Actors.urls')),
    path('Movies/', include('Movies.urls')),
    path('api/movies/', include('Movies.api.v1.urls')),
    path('api/accounts/', include('Accounts.api.v1.urls')),
    path('api/actors/', include('Actors.api.v1.urls')),
]
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie-app/movie_app/templates/base_layout.html
{% load static  %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>

{% include 'navbar.html' %}

{% block content %} {% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

</body>
</html>

movie-app/movie_app/templates/home.html
{% extends 'base_layout.html'%}

{% block title %} Movie-App {% endblock %}
{% block content %}
<div class="col-10 offset-1 mt-1">
    <div
            id="carouselExampleDark"
            class="carousel carousel-dark slide"
            data-bs-ride="carousel"

    >
        <div class="carousel-inner">
            <div class="carousel-item active" data-bs-interval="10000" style="height: 90vh;">
                <img src="/media/background-1.jpg" class="d-block w-100 img-fluid h-100" alt="..."/>
                <div class="carousel-caption d-none d-md-block">
                    <h6 class="fs-1 d-block text-white text-decoration-none" href="#">
                        Movie Lib
                    </h6>
                    <h5
                            class="fs-4 font-monospace text-white text-decoration-none shadow-lg"

                    >
                        Some stuff we find awesome
                    </h5>
                    <a type="submit" class="btn btn-sm btn-success col-4 offset-1 shadow-lg "
                       href="{% url 'Movies:all-Movies' %}">Movies</a>
                    <a class="btn btn-sm btn-primary col-4 ms-3 shadow-lg "
                       href="{% url 'Actors:all-Actors' %}">Actors</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

movie-app/movie_app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #b5d5ff;">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Movie-App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'Actors:all-Actors' %}">Actors</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Movies:all-Movies' %}">Movies</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About-US</a>
        </li>

      </ul>

    </div>
 {% if request.user.is_authenticated %}
    <h5>Hello {{user.username}}</h5>
    <a  class="nav-link" href="{% url 'logout' %}">LogOut</a>
    {% else %}
       <a  class="nav-link" href="{% url 'login' %}">Login</a>
       <a  class="nav-link text-light" href="{% url 'accounts:signup' %}">Sign-Up</a>
{% endif %}
  </div>
</nav>